# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df748d588ac3e3b176ed8ed1923da204717fbbdd3c74e6fa30d103ed24c3d628afe9632fb8d8ae69529526055b5f9b8f2cf61bc8d2c750ee37f05d2f484db94b

test:
  secret_key_base: 3a739b83c5fc3ff537902771db07c4a9383686e014e5394512b9568e6af49bd7a843ca5c551a9baca8cfc9e6fe9f9e9a9fc9b805a4a9321e41e3b57e55cc52e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
